import type { Metadata } from "next";
import ReduxProvider from "@/store/Provider";
import { openSans } from "@/fonts";
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`${openSans.className}`}>
            <body className="antialiased">
                <ReduxProvider>{children}</ReduxProvider>
            </body>
        </html>
    );
}
